name: magicmagnet
author: Pedro Lemos (@pedrolemoz)
repository: https://github.com/pedrolemoz/MagicMagnet

description: Get magnet links from internet without any effort

publish_to: 'none'

version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
